CREATE TABLE users
(
	ID INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	username VARCHAR(20) UNIQUE,
	password VARCHAR(40),
	e-mail VARCHAR(50),
	userlevel INT(1)
);

CREATE TABLE reservations
(
	ID INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	start_time DATETIME,
	duration INT(2),
	user_ID INT UNIQUE,
	room_ID INT UNIQUE
);

CREATE TABLE room
(
	ID INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	user_IDs INT
);
